version: '3.7'
services:
  db:
    image: postgres:14.3
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_DB: postgres_db
      # POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      # PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:6.10
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mostafa@negim.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - db
volumes:
 db-data:
 pgadmin-data:
networks:
  db:
    name: db_network
